name: signalr_core
description: ASP.NET Core SignalR Client written for Dart that is platform-independent, and can be used on both the command-line and the browser.
version: 1.1.1+1
publish_to: none
homepage: https://github.com/jamiewest/signalr_core

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  http: ^1.1.0
  logging: ^1.2.0
  meta: ^1.9.1
  tuple: ^2.0.2
  web_socket_channel: ^2.4.0
  sse_channel:
    git: https://github.com/bull-xu/sse_channel.git
  equatable: ^2.0.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.8
